[package]
name = "dbs-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dragonball = { git = "https://github.com/RainaYL/kata-containers", branch = "rainax/restruct_intr_pr", features = [
    "virtio-blk",
    "virtio-fs",
    "virtio-vsock",
    "virtio-net",
    "vhost-net",
    "hotplug",
    "dbs-upcall",
    "vhost-user-net",
    "host-device"
] }
clap = { version = "4.5.60", features = ["derive"] }
serde = "1.0.228"
serde_derive = "1.0.228"
libc = "0.2.183"
seccompiler = "0.5.0"
log = "0.4.29"
kvm-bindings = "0.14.0"
kvm-ioctls = "0.24.0"
thiserror = "1"
nix = "0.31.3"
anyhow = "1.0.102"
vmm-sys-util = "0.15.0"
slog = "2.8.2"
slog-term = "2.9.2"
slog-json = "2.6.1"
slog-scope = "4.4.1"
slog-stdlog = "4.1.1"
serde_json = "1.0.149"
crossbeam-channel = "0.5.15"
